### ISSUE TITLE
Fix stackblitz example

### ISSUE THREAD

**Issue by KatFishSnake** [nvh95/vitest-preview#15]
## Describe the bug

When clicking `Try now` the stackblitz instance doesn't seem to be able to build the modules, reinstalling the module manually works https://stackblitz.com/edit/vitest-preview-fh8b6e

```
~/projects/vitest-preview
❯ npm install && npm start
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: request to https://nr.staticblitz.com/vitest-preview failed, reason: socket hang up

error Command failed with exit code 1

~/projects/vitest-preview
```

## Screenshots

<img width="970" alt="Screen Shot 2022-10-31 at 12 15 17 PM" src="https://user-images.githubusercontent.com/12003520/199091251-1fea1202-6606-4e3a-8f43-4b973f5b61ca.png">

## Reproduce

Go to http://bit.ly/try-vitest-preview, try to use the example

Please provide a minimal [reproduction](https://stackoverflow.com/help/minimal-reproducible-example) for the issue. Thanks.

You can use one of the following options to reproduce the issue:

- Create a new GitHub repository (recommended): https://github.com/new
- Create a StackBlitz project: https://stackblitz.com
- Create a sandbox on CodeSandbox: https://codesandbox.io/s

## Expected behavior

- The example works as expected

## Environment (please complete the following information)

- OS: macOS 12.5.1
- Browser: Chrome 106.0.5249.119

**Comment by nvh95** [comment]
Hi @KatFishSnake.

Thanks for your help. I am not sure the reason it couldn't install the dependencies. I guess it's an issue from stackblitz. I just manually reinstalled the package and it works fine now.

**Comment by nvh95** [comment]
@all-contributors please add @KatFishSnake for example
